gcp_service_account = """
{
  "type": "service_account",
  "project_id": "lqairmh-agbg-iberia-song-ccai",
  "private_key_id": "abcdef1234567890abcdef1234567890abcdef12",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkq...FjAgMBAAECggEAQ7...\\n-----END PRIVATE KEY-----\\n",
  "client_email": "streamlit-access@lqairmh-agbg-iberia-song-ccai.iam.gserviceaccount.com",
  "client_id": "123456789012345678901",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access%40lqairmh-agbg-iberia-song-ccai.iam.gserviceaccount.com"
}
"""
